/** ***************************************************************************
 * @file
 *
 * @brief Contains catch main runner for test cases
 *****************************************************************************/
#include "prog1.h"

// leave this untouched.
void makeCATCH(int& myargc, char**& myargv)
{

    myargc = 1;
    myargv = new (nothrow) char* [myargc];

    myargv[0] = new (nothrow) char[strlen("x64\\debug\\prog1.exe") + 1];
    strcpy(myargv[0], "x64\\debug\\prog1.exe");
}

// do not edit this file at all.  I will append test cases in here to grade your required parta.
